CREATE DATABASE  [CloudPic]
COLLATE Croatian_CI_AI;
GO

USE [CloudPic]
GO

CREATE TABLE [User]
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	[Password] NVARCHAR(150) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	LoginProvider NVARCHAR(10) NOT NULL,
	RegisterDate DATETIME NOT NULL
);
GO

CREATE TABLE [Plan]
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	PricePerDay DECIMAL NOT NULL,
	PhotosPerDay INT NOT NULL,
	StorageSize INT NOT NULL,
	MbPerDay INT NOT NULL
);
GO

CREATE TABLE UserPlan
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	UserId INT FOREIGN KEY REFERENCES [User](Id) NOT NULL,
	PlanId INT FOREIGN KEY REFERENCES [Plan](Id) NOT NULL,
	DateFrom DATETIME NOT NULL,
	DateTo DATETIME NULL
)
GO

CREATE TABLE Photo
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	[Guid] NVARCHAR(36) NOT NULL,
	UserId INT FOREIGN KEY REFERENCES [User](Id) NOT NULL,
	UploadDate DATETIME NOT NULL,
	[Description] NVARCHAR(36) NOT NULL,
	[Format] NVARCHAR(10) NOT NULL,
	SizeInMb DECIMAL NOT NULL,
);
GO

CREATE TABLE Hashtag
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	PhotoId INT FOREIGN KEY REFERENCES Photo(Id) NOT NULL,
);
GO

CREATE TABLE LogType
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
);
GO

CREATE TABLE [Log]
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	UserId INT FOREIGN KEY REFERENCES [User](Id) NOT NULL,
	LogTypeId INT FOREIGN KEY REFERENCES LogType(Id) NOT NULL,
	ObjectId INT NOT NULL,
	LogDate DATETIME NOT NULL,
);
GO


INSERT INTO [User] VALUES ('brunoubica@gmail.com', '123456547564', 'Bruno Loncar', 'STOKEN-123', '2020-01-01')
SELECT * FROM [User]

INSERT INTO [Plan] VALUES ('Free', 0, 5, 10, 50), ('Pro', 0.4, 50, 100, 500), ('Gold', 1, 200, 2000, 500)